CompanyName.Sklep.Web/Controllers/ArticleController.cs
using CompanyName.Sklep.Services.Interfaces;
using CompanyName.Sklep.Services.Models;
using CompanyName.Sklep.Web.Filters;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CompanyName.Sklep.Web.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleService _articleService = null;

        public ArticleController(IArticleService articleService)
        {
            this._articleService = articleService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ArticlesListViewModel model = null;

            model = _articleService.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Create(Boolean isModal = false)
        {
            if (isModal)
                return PartialView();
            else
                return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateArticleViewModel article)
        {
            ActionResult view;

            if (ModelState.IsValid)
            {
                if (_articleService.Save(article))
                    view = RedirectToAction("Index");
                else
                    view = View(article);
            }
            else
                view = View(article);

            return view;
        }

        [HttpGet]
        public ActionResult EditPrice(Int32? id)
        {
            EditArticlePriceViewModel model = null;

            ActionResult view;
            if (id.HasValue)
            {
                model = _articleService.GetForEdit(id.Value);

                if (model == null)
                    view = HttpNotFound("Item does not exist");
                else
                    view = View(model);
            }
            else
                view = new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return view;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPrice(EditArticlePriceViewModel article)
        {
            ActionResult view;

            if (ModelState.IsValid)
            {
                //if (_articleService.UpdatePrice(article))
                //    view = new HttpStatusCodeResult(HttpStatusCode.OK);
                //else
                //    view = new HttpStatusCodeResult(HttpStatusCode.NotModified);
                _articleService.UpdatePrice(article);
                view = RedirectToAction("Index");
            }
            else
                view = View(article);

            return view;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Int32? id)
        {
            ActionResult view;

            if (id.HasValue && id > 0)
            {
                _articleService.Delete(id.Value);
                view = RedirectToAction("Index");
            }
            else
                view = new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return view;
        }
    }
}

CompanyName.Sklep.Web/Controllers/UserController.cs
using CompanyName.Sklep.Services.Interfaces;
using CompanyName.Sklep.Services.Models;
using CompanyName.Sklep.Web.Filters;
using CompanyName.Sklep.Web.Helpers;
using FluentValidation;
using Microsoft.Practices.Unity;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CompanyName.Sklep.Web.Controllers
{
    public class UserController : Controller
    {
        private IUserService _userService;
        private IRoleService _roleService;
        private IUnityContainer _container;

        public UserController(IUserService userService
            ,IRoleService roleService
            ,IUnityContainer container)
        {
            this._userService = userService;
            this._roleService = roleService;
            this._container = container;
        }

        [HttpGet]
        public ActionResult Index(String message)
        {
            UsersListViewModel model = null;

            model = _userService.GetAll();

            if (!String.IsNullOrWhiteSpace(message))
                ModelState.AddModelError("Message", message);

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(Int32? id)
        {
            ActionResult view;

            if (id.HasValue && id.Value > 0)
            {
                var model = _userService.GetForEdit(id.Value);

                if (model == null)
                    view = RedirectToAction("Index");
                else
                    view = View(model);
            }
            else
                view = RedirectToAction("Index");

            return view;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditUserViewModel user)
        {
            ActionResult view;

            user.Roles = _roleService.GetAll().ToList();
            if (ModelState.IsValid && _userService.Update(user))
                view = RedirectToAction("Index");
            else
            {
                if (!String.IsNullOrWhiteSpace(user.Message))
                    ModelState.AddModelError("Message", user.Message);

                view = View(user);
            }

            return view;
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new CreateUserViewModel();
            model.Roles = _roleService.GetAll();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateUserViewModel user)
        {
            ActionResult view;

            user.Roles = _roleService.GetAll().ToList();
            if (ModelState.IsValid && _userService.Save(user))
                view = RedirectToAction("Index");
            else
            {
                if (!String.IsNullOrWhiteSpace(user.Message))
                    ModelState.AddModelError("Message", user.Message);
                view = View(user);
            }

            return view;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Int32? id)
        {
            ActionResult view;

            var validator = _container.Resolve<IValidator<Int32?>>();
            var result = validator.Validate(id);

            if (result.IsValid)
            {
                _userService.Delete(id.Value);
                view = RedirectToAction("Index");
            }
            else
                view = RedirectToAction("Index", new { message = result.Errors.First().ErrorMessage });


            return view;
        }
    }
}

CompanyName.Sklep.Web/Views/Shared/_HeaderPanel.cshtml
@model String
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Articles <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Show all", "Index", "Article")</li>
                        <li>@Html.ActionLink("Create new", "Create", "Article")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Users <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Show all", "Index", "User")</li>
                        <li>@Html.ActionLink("Create new", "Create", "User")</li>
                    </ul>
                </li>
            </ul>
            @using (Html.BeginForm("Logout", "Account", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <input type="submit" value="Logout from: @Model" class="btn btn-warning" />
                    </li>
                </ul>
            }
        </div>
    </div>
</nav>

CompanyName.Sklep.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CompanyName Oleh datsko test app</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @if (TempData.Keys.Contains("User"))
    {
        @Html.Partial("_HeaderPanel", (String)TempData["User"])
    }
    
    <div class="container body-content">
        <div class="container">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>